# Generated by Django 3.0.5 on 2020-04-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200425_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='Imagen 0', max_length=200),
            preserve_default=False,
        ),
    ]
